project:
  type: website
  output-dir: docs
  
website:
  description: "Yinghe Liu's personal website and blog."
  title: "Liu's Journey"
  navbar:
    collapse-below: lg
    left:
    - Lifestory.qmd
    - Academe.qmd
    - CV.qmd
    right:
    - About.qmd
    tools:
    - icon: discord
      href: https://discordapp.com/users/1143984722620448839
    - icon: github
      href: https://github.com/YingheLiu5579
    - icon: envelope
      href: mailto:yingheliu@outlook.com
    - icon: rss
      href: index.xml
  back-to-top-navigation: false
  site-url: https://yingheliu5579.github.io/Liu-s_Journey/
  open-graph: 
    locale: en_US
  google-analytics: G-EKVMX1KG8P
    
format:
  html:
    theme: flatly
    css: styles.css
    highlight:
      theme: github
      version: 9.18.1
    smooth-scroll: true
    citations-hover: true
    footnotes-hover: true
    title-block-banner: True
    code-fold: true
    code-summary: "Show the code"
    code-block-bg: true
    code-copy: false
    code-link: true
    anchor-sections: true
    link-external-icon: false
    link-external-newwindow: true
    grid:
      sidebar-width: 250px
      body-width: 900px
      margin-width: 300px

editor: visual
comments:
  hypothesis: 
    theme: clean
    showHighlights: true

execute:
  freeze: auto
  
lightbox: true