---
title: "Academe"
date-modified: "2024-1-3"
listing:
  contents: posts
  sort: false
  type: default
  categories: false
  include:
    categories: "Academe"
---

I spent the first eighteen years of my life in a small city in central China, where educational resources were limited, and everyone was striving for the opportunity to move to bigger cities. Standardized exams acted as ruthless filters, stifling individual exploration and creativity. During my high school years, I continually pondered what kind of person I was and explored various philosophical viewpoints. The exploration of thinking itself fascinated me, and eventually, I chose psychology as my undergraduate major.

In the Chinese context, psychology is a vast concept, and I didn't understand what studying psychological phenomena systematically entailed. During my first two years in college, I explored different courses in psychology. These courses were all intriguing, but most importantly, they helped me realize that psychology is an empirical discipline. The psychological perspective that intrigued me the most was viewing psychological phenomena from cognitive and individual development perspectives. No cognitive phenomenon arises out of thin air; it is based on biological structures. Moreover, over time, our cognition is continually shaped.

In the vast realm of psychology, the "chess study" caught my attention. This resonated with my passion for board games, and you can find more specific details in the articles I share on my blog. "Executive function" is at the core of the research, but most undergraduate education provides general knowledge and is insufficient to answer all questions comprehensively. Therefore, in my junior year, I decided to further my education and seek more knowledge about "executive function."

I was fortunate to have the opportunity to explore the academic world during the summer break of my junior year. I first joined the [PRESH project](https://csc.la.psu.edu/research/funded-research-projects/parent-regulation-engagement-stress-and-health-presh/) led by Professor Lunkenheimer at Penn State. [The research group](https://pcd.la.psu.edu/meet-the-team/) focused on how parents and children interact and whether this parent-child relationship is influenced by the parents' own experiences. A classic scenario was teaching children to manage their behavior, and the research group set up a simulated daily interaction laboratory setting for this purpose. My role in this project was to collect Electrodermal Activity (EDA) data, and I have written several blog posts analyzing the challenges we faced regarding EDA data.

I also joined [another research group](https://gilmore-lab.github.io) at Penn State, led by Professor Gilmore. His research focused on two major areas: the early developmental curve of human vision and the issue of replicability. One significant reason I joined this group was my realization of the importance of data collection in psychological research and the challenges encountered in practice, such as EDA. My task was to create a handbook for a data-sharing platform to make it easier for people to share data. This information platform, dedicated to developmental psychology, is called [Databrary](https://nyu.databrary.org).

At the same time, I attempted to design research from the perspective of a data analyst to provide more evidence about the challenges of EDA replicability, but progress has been slow. My current goal is to finalize the proposal by the end of January and seek further guidance.

------------------------------------------------------------------------

**Check these posts to know about my academic passion!**
