---
title: "Academe"
draft: true
lang: zh
---

我人生的前十八年在中国中部的一个小城市度过，在那里教育资源稀缺，大家都在努力为了少数去到大城市的机会努力着。标准化的考试像一个无情的大过滤机器，扼杀了个体个性的探索。我在高中时期不断的思考自己是一个什么样的人，在这期间了解到了许多不同的思想观点。对于思考能力本身的探索令我着迷，最终我选择了心理学作为本科专业。

在中文语境里，心理是一个庞大的概念，我并不了解系统性学习心理现象是什么样的。在大学的前两年，我尝试了心理学领域的不同课程。这些课程都很有趣，但跟重要的是让我了解到心理学是一门基于实证主义的学科。~~心理学更应当被称作“心/理学”而非“心理/学”~~。最令我着迷的心理学观点是从认知和个体发展的角度看待心理现象。任何认知现象都不是凭空出现的，而是基于生物结构的。同时在时间的演进之中，我们的认知不断被塑造。

在广阔的心理学研究中，“chess study” 引起了我的注意。这和我本身本身就是一个棋类游戏爱好者有关，更具体的内容可以关注我在博客中分享的文章。“执行能力”是研究的核心问题，但现有的本科教育大都是通识性质的教育内容，难以完全解答所有的疑问。因此，我也在大三的时候决定为了进一步的教育努力，去了解关于”执行能力“的更多。

我很幸运，在大三的暑假得到了进入课题组了解学术体系的机会。我首先加入的是PRESH项目，由penn state 的professor Lunkenheimer所领导。 课题组关注父母和儿童是如何互动的，这种亲子关系是否收到家长自身的经历影响。一个经典的情景便是教育儿童管理自己的行为，课题组基于此设立了一个模拟日常互动的实验室场景。我在其中的职责是收集EDA数据，关于EDA数据我特别写了数篇博客来分析我们面临的挑战。

我加入的另一个位于penn state的课题组的PI是 Gilmore教授。他关注的两个问题是人类视力的早期发展曲线和可重复性问题。我加入课题组的一个重要原因便是我意识到了数据收集在心理学研究中的重要作用，以及在实践过程中（如EDA）的挑战。我的任务是创建一个数据共享平台的手册来帮助人们更容易分享数据，这个专注于发展心理学的信息平台平台叫做Databrary。

同时，我也尝试从many analyst的角度设计研究在提供更多关于可EDA重复性挑战的证据，但仍在缓慢推进之中。我目前的目标是在一月底完成开题报告的最终版本，并进一步尝试寻求其他指导。
