---
title: "Lifestory"
date-modified: "2024-1-12"
draft: true
lang: zh
---

我出生在中国中部的一座普通的小县城，在家里还有四个姊妹，我是最小的一个。家里孩子们并不来源于同一位母亲，只有我的另一位年龄姐姐年龄相仿。为了更好给我们两个的教育资源，我们搬到了距离最近的城市之中，洛阳市。在那个计划生育的时代，每个家庭都只被允许生育一个后代。或许是为了照顾那个年代传统的重男轻女情节，第一胎如果是女孩的话可以再生育一个后代，我也因此幸运诞生。

六岁前的记忆对我已是极为模糊，最早我能追溯的清晰记忆是五岁时候我一个人跟在父母身后的孤单无助。当然，最早可追溯的记忆来源这个年龄且是负面的其实是一个普遍现象。下一个可明确描述的记忆则是一年级第一次没有母亲陪伴，和其他孩子一起坐在教室中的大哭大闹。我是同班学生中年龄最小的几个，那是个入学年龄还没有硬性准则的年代。

现在回想起来，我的小学时光大体是欢乐的，一段无忧无虑的生活。我的表现并不出众，从来都不是被老师当作榜样的那个“别人家的孩子”。每天最担心的便是没写作业被老师批评叫家长，或者放学后要去上补习班。那时我有几个关系密切的玩伴现在也断了联系，或许他们现在都开始缤纷的新生活。我也经历了校园欺凌，目睹了家庭暴力，是好朋友和母亲的陪伴让我度过了那段岁月。

初中的岁月则是一段令我回味的，希望重新经历的自我探寻之旅。我第一次感受到了性吸引力，第一次有一段维持了数年的，无话不说的友情，有了第一次出国旅游的经历，同时经历了第一次的死亡焦虑。学校里的知识是新颖的，我开始系统性的学习不同的科目，一切都在等待着我去探索。当然。我也可以回想起这个时期自己无数的“中二”行为，我好希望能从我的记忆力删除这些尴尬时刻。

高中生活则是有创伤性的。高中第一年仍是充满了学习新知识和结交新朋友的欢愉，但第二年开始的为高考准备的氛围则令我开始焦虑，这也最终压垮了我。我难以在所有学科中都保持兴趣，令我“偏科”的表现在标准化测试中并不有利。同时，随着计划生育的结束，我父母决定生育一个新的孩子，我有了一个小我十岁的弟弟。却不成想母亲的产后抑郁撞上了过去的旧闻，一场前所未有的冲突在家庭内部爆发了。家庭的破碎和学业的高压令我我难以适从，我不断的问自己和周围的人“我是谁？”，一些过去向往的憧憬逐渐破碎。

高考在中国语境中是如此特殊，一次考试就能决定你未来的几十年。我在高考前的新年决定放弃高考，选择出国留学。生活中的经历促使我对思考和行为进行思考，究竟什么是思考能力呢。我有机会前往异国他乡学习自己感兴趣的内容，特别需要感谢我家人的理解和支持。高中的最后一年在我对未来的不安中度过。

大学生活的开始伴随着黑天鹅事件，新冠疫情。第一年我被迫留在国内，在2021年中delta流行株爆发的前夕前往了美国。第二年同样是在口罩中度过的，大学里的早期课程多是通识课程，我并没有很多学分来选择我感兴趣的内容。这两年我在适应新的文化，也了解了什么是心理学。我也终有了属于自己的空间，重新构建我想要的未来和生活。进一步了解了我感兴趣的领域后，我决定努力深度参与学术研究，在大三学期的暑假加入了课题组开始从基础的数据收集做起。

写在2024年的年初，我目前的生活仍是具有很大不确定性的。我在努力寻找一份能让自己呆在学术领域的工作，也在考虑其他的可能性。我的前两个十年充满了探索，我也希望能继续在未来不断挑战自己。
