---
title: "2024展望"
author: "Yinghe Liu"
date: "2024-1-2"
date-modified: "2024-1-2"
categories: [Non-Academe]
description: "是时候回顾过去一年并为未来做计划了！"
draft: true
lang: zh
---

节日作为一个社会法事都被赋予了某个特定的含义，这或许是为了纪念某一个体或重大事件。但对我熟悉的人都知道我不庆祝节日，只庆祝假期，因为对我而言每一天都没有任何的特殊性。我只感激空余的时间，并不会特别将其赋予意义。实际上，我最讨厌的两个词就是意义和证明，他们都被赋予了广阔而复杂的含义，我认为使用“作用/目的”和“说明/支持”才是大多数语境的最佳表达。或许有一天我会特别写一篇博客来分享我的哲学观点。
回到节日的话题，为什么我选择在新的一年伊始来写规划和总结呢，这似乎和我之前的叙述有矛盾。我难以将其中微妙的心境变化描述，或许是手机屏保上日期的变更，从习惯了数百日的一个数字变为了另一个新的数字，陌生又不可逃避的。这中人为附加的分类结构在提醒我我的假期余额不足了，焦虑迫使我回顾我的过去一年。另外的原因是新学期的邻近，我或许在将来的几周内都难以找出一个空余的时间短来放松的思考。
我最明显的感知是过去一段时间身体状况的下降。在6月到9月的时候我曾保持一周至少两个小时的剧烈运动，但到了年底我却每天都疲倦不堪，就连出门买菜的动力也丧失了。这种变化是逐渐的，或许是十月的某一天我本当锻炼身体的时候一些条件打断了进程，后边就是大摆烂的过程了。哦，我想起来了，是秋冬换季的时候感染了covid19，这导致我放弃了原本的进程。我希望接下来的一年我能够找回锻炼的节奏，至少能保证一定的生物节律。
人际关系呢？我最多的时间仍投资在一段维持了四年的友情，FEI陪伴了我无数个日夜。其他在大学前的朋友只有个别还保持的偶尔的节日问候，另外的大部分则是默默躺在通讯录里，岁月静好。有时我会突然想念起过去的一些经历并产生问候过去朋友的冲动，可想到我短时间内没有回国的计划，我又只能无奈放弃。我宁愿不去带来失望。我还结交了一些新的朋友，他们大都是学校内的课友。除此之外，我的父母仍会定期给我打电话，我也有时和姐姐互相分享生活中的苦难。浪漫关系也有没任何进展，我仍旧在享受独身的时光。人际关系的维持难以强求，有目的性的追求人际关系很累。~~一个人生活真的是太爽了！😝~~ 
在学业上，我做出了巨大的突破。在年初的时候，我认定了进一步的学术研究作为未来几年的长期计划，并确定了感兴趣的领域。我保持了课程的表现并开始阅读一些文献。不得不承认，一些文献十分难以阅读，其中包含的一些词汇仍是我最大的阅读障碍。但是当我开始熟悉了学术文献的结构，我便不再抵触阅读了。我还加入了两个课题组，原来行为科学的研究的流程比我想象的要更加朴素。我也深深佩服那些天才的实验设计和构想。还有就是尝试承担了一个TA的责任，可惜的是受限于自身知识的有限我并没有很好的帮到那门课的学生们，对此我深感自责。
学术将接下来一段时间的重要目标。我故意放弃了23年末的申请窗口，因为我还不资格来成为phd学生。在未来几周，我将完善关于EDA可重复性的的开题报告并尝试寻求支持。除此之外便是尝试找一个职位留在学术界了，这又是一个令人头疼的大事件。希望我能找到一个感兴趣的课题组愿意收留我 &#x1F979;。