---
title: "Prospects of 2024"
author: "Yinghe Liu"
date: "2024-1-2"
date-modified: "2024-1-2"
categories: [Non-Academe]
description: "Time to summerize and make plans!"
---

Holidays, as a societal tradition, are often imbued with specific meanings, perhaps to commemorate a person or a significant event. However, those familiar with me know that I don't celebrate holidays; I only observe vacations because, to me, every day holds no particular “meaning". I simply appreciate the free time and don't assign any special meaning to it. In fact, the two words I dislike the most are "meaning" and "proof," as they both carry broad and intricate connotations. I believe that "purpose" and "support" are often better expressions in most contexts. Perhaps one day, I will write a blog post to share my philosophical viewpoints.

Now, back to the topic of holidays, why do I choose to plan and reflect at the beginning of a new year, which seems contradictory to my previous narrative? It's challenging to describe the subtle shift in my mindset, perhaps it's the change in the date on my phone's lock screen, going from a number I've been accustomed to for hundreds of days to a new and unavoidable one. This artificial categorization reminds me that my vacation balance is running low, prompting anxiety and leading me to review the past year. Another reason is the upcoming new semester, during which I might struggle to find spare time for relaxation.

My most noticeable perception is the decline in my physical condition over the past months. From June to September, I maintained vigorous exercise for at least two hours per week, but by the end of the year, I felt exhausted every day, even lacking the motivation to go grocery shopping. This change was gradual, and perhaps it was one day in October when certain circumstances disrupted my exercise routine, leading to a gradual decline. Oh, I remember now, I got infected with COVID-19 during the seasonal transition from autumn to winter, which caused me to abandon my previous routine. I hope that in the coming year, I can regain a rhythm of exercise, at least maintaining a certain biological rhythm.

As for interpersonal relationships, most of my time is still invested in a friendship that has lasted for four years, with FEI accompanying me through countless days and nights. Other friends from before college only occasionally exchange holiday greetings, while most of them remain silently in my contact list, a testament to the passage of time. Sometimes, I suddenly miss some past experiences and have the urge to greet old friends, but considering I have no plans to return home in the near future, I can only reluctantly give up. I'd rather not bring disappointment. I have also made some new friends, most of whom are classmates at school. Apart from that, my parents still call me regularly, and I sometimes share life's hardships with my sister. There has been no progress in romantic relationships, and I continue to enjoy my single life. Maintaining interpersonal relationships is difficult to force, and purposefully pursuing them can be exhausting. ~~Being single is truly enjoyable!😝~~

In academics, I have made significant breakthroughs. At the beginning of the year, I set academic research as a long-term plan for the next few years and identified areas of interest. I maintained my performance in courses and began reading some literature. I must admit that some of the literature is challenging to read, and some of the vocabulary remains my biggest reading obstacle. But as I became familiar with the structure of academic literature, I no longer resisted reading. I also joined two research groups, and the process of behavioral science research turned out to be simpler than I had imagined. I deeply admire the genius experimental designs and concepts. I also attempted to take on the responsibility of a TA, but unfortunately, limited by my own knowledge, I didn't help the students in that course much, and I feel deeply responsible for that.

Academics will be a significant focus for the next period. I deliberately gave up the application window at the end of 2023 because I am not yet qualified to be a Ph.D. student. In the coming weeks, I will refine my proposal on EDA repeatability and seek support. Additionally, I will try to find a position to stay in academia, which is another headache. I hope to find a research group that interests me and is willing to take me in 🥹.
