---
title: "近期游戏回顾"
author: "Yinghe Liu"
date: "2024-1-16"
categories: [Non-Academe]
description: "回顾我近期玩的游戏：巫师3，艾尔登法环，传送门2"
lang: zh
draft: true
---

在入手了新的steamdeck oled之后，我的设备终于拥有了足够的性能来运行一些比较大型的游戏了，其中最令我沉迷的便是巫师3和艾尔登法环。除此之外我还和FEI尝试了很多双人联机游戏，这些游戏质量参差不齐。 

## 巫师3:狂猎 

巫师三入库其实有一年了，但之前的游玩体验一直卡在新手教程，新设备的加入令我终于有动力再次于新的操作平台尝试。我在圣诞节假期前后花费了五十个小时左右的时间，完成了巫师三的主线剧情，停止在了Ciri的最后一站前。由于之前已经在网飞看过了衍生剧集，我其实已经了解过剧情的最终结局，我停止的原因是对于游戏的剧情已经没有了太多的兴趣，对于找女儿的剧情发展我已经没有了太多的期待。我甚至购买了DLC，可能要等到下一次假期才会拾起来吧。 

我很喜欢巫师三的世界架构，庞大并且完善。游玩过程中最有趣的体验来自剧情发展的自主选择，玩家的选择会影响到后续的剧情发展。我在游戏中选择了尽可能的追求保护所有周围的人，最纠结的选择是在树心的剧情中，我不断读档来尝试不同的选择。在普通难度下，游戏战斗并没有很大的挑战，对于我这种FPS苦手来说非常友好。我非常喜欢探索地图带给我的新鲜感，仅仅是清理问号就让人沉迷。当然，作为一款发售了好几年的经典作品，我也在游玩过程中遇到模型显示粗糙的问题，这或许是游戏的一个缺点吧。 

## 艾尔登法环 

艾尔登法环太好玩了，非常符合我胃口的作品！我已经沉迷了将近一百个小时，这还是一周目的情况下。我只差最后的艾尔登之兽作为主线的最后一个BOSS就能完结主线了。当然，最后的这个BOSS的设计还是很想让人吐槽的，我近战狂战士不得不化身走路模拟器，希望我能在未来的几天内不再卡关。

没有多余的新手指引和剧情，好！我反感那些故事叙述优先于游戏性的设计，给我一种强迫完成主线内容的使命感。在艾尔登法环中，我可以自由的探索地图，自由的选择任务线。在逐渐的摸索和对文本的拼凑下解读隐藏的故事。最棒的就是战斗系统，多种多样的武器选择。我可以选择双手武器，单手武器，盾牌，法术，弓箭，投掷武器，甚至是拳套。在没有任何剧透的情况下选了狂战士，不得不说开荒还是有些挑战的。很期待其他不同的流派，已经在准备下个周目当一个高贵的法师逃课了。还有其他祈祷，召唤，无不满足我的好奇心。

当然，缺点也有. 画面的渲染非常精致，可以截图当作壁纸的优美，这对性能有很高的要求，我的steamdeck只能稳定在三十帧到四十帧，在跑图的情况下会出现画质割裂的情况。另一个槽点可能就是游戏的难度了。游戏没有提供难度档位的选择，这种没得选择的情况对我来说很省心，懒得纠结，但严格的死亡惩罚可能会劝退一些玩家。我是rogue-like游戏的忠实粉丝，所以这种死亡惩罚对我来说并不是很大的问题就是了。

## 传送门2

难以想象的大师之作！我最开始没有很大的期望，毕竟是十多年前的老游戏，只是因为其久负盛名又恰好是Valve的作品，所以我才会尝试。在大量好评的心理预期背景下，我被这款游戏的设计惊艳到了。
丝滑，这是我游玩的第一感。画面细腻，动作流畅，没有任何的卡顿。我本以为老游戏会有粗略的建模，就像巫师3，传送门2告诉我什么是行业明灯。写进游戏名称的核心游戏设计令人惊叹，我在游戏中不断的使用传送门，不断的在空间中穿梭，不断的解决谜题。最难以置信的是物理引擎的架构，这么丝滑的体验究竟是怎么写出来的！
我甚至不舍得游玩，每一点游戏内容的消耗都令我感到不舍。廉价的售价，较低的性能要求，优秀的画质，绝佳的游戏创意，传送门2是我迄今为止见过最值得推荐给所有人的游戏，或许没有之一。

## 结语
这便是我这个圣诞假期的游戏体验中最值得推荐的三款游戏，他们都值得你花费时间去体验。~~如果我没有及时更新的博客，我一定是在沉迷游戏。~~ 接下来我会更新一些其他体验过的游戏，敬请期待。